# Input-Ouput operations to files

In this video I'll show you a little bit of Input-Output operations o files. I'll be brief because I'll talk about it later with other tools. However, this is also important to know.

Files can be open by using the function open(), which takes two arguments: the first is the file address; and the second
is the opening mode. There are some mode to open a file. The most common/useful are listed below:
    
1. __r__ : This mode indicate that file will be open for reading only
2. __w__ : This mode indicate that file will be open for writing only. If file containing containing that name does not exists, it will create a new one
3. __a__ : This mode indicate that the output of that program will be append to the previous output of that file
4. __r+__ : This mode indicate that file will be open for both reading and writing

# TXT Files

In [2]:
#Let's open a stream to write data in a text file

datafile = open('file.txt', 'w+') 

# once this file doesn't exist it will create a new one
# if you don't specify the action, it will open as reading

In [3]:
datafile

<_io.TextIOWrapper name='file.txt' mode='w+' encoding='cp1252'>

In [4]:
datafile.name

'file.txt'

In [5]:
datafile.mode

'w+'

In [6]:
datafile.closed

False

In [7]:
# Now let's create some data to further put it in the file

products = [['ProductID', 'Name', 'Price'], ['0001', 'Shoes', '49.99'], ['0011', 'Hat', '19.99'], ['0021', 'T-shirt', '29.99']]

In [8]:
# Now we'll use join to create a single string for each row of list data and write it into the file

for line in products:
    datafile.write("%s\n" % ",".join(line))

In [9]:
# Now we can close this stream
datafile.close()

# and we can check if it is closed
datafile.closed

True

In [10]:
# Now we can open a new stream to read that data

data = open('file.txt', 'r')

In [11]:
data

<_io.TextIOWrapper name='file.txt' mode='r' encoding='cp1252'>

In [12]:
# to read the contents of our file we can do .read()

print(data.read())

ProductID,Name,Price
0001,Shoes,49.99
0011,Hat,19.99
0021,T-shirt,29.99



In [14]:
# to read the contents of our file we can do .read()

print(data.read())

In [11]:
data.close()

# CSV Files

A particularly useful file format for data scientists is the csv format (comma separatted values). To easily handle csv files
we can use the csv package, which we need to import first.

In [27]:
import csv
# we will load the numpy to generate 
# a random matrix of numbers, we will talk more about numpy in the 4th lecture
import numpy

In [38]:
matrix = numpy.random.random((5,5))
print(matrix)

[[0.6298589  0.91638974 0.41438391 0.09860005 0.46438036]
 [0.92688464 0.77061813 0.17839555 0.99206763 0.33428337]
 [0.4906214  0.39286379 0.5086225  0.98485958 0.93633876]
 [0.06972556 0.61300842 0.98065472 0.4581125  0.13982784]
 [0.52806234 0.33318942 0.70593334 0.77576271 0.38000097]]


In [39]:
file = open("matrix.csv","w+")

In [40]:
# Return a writer object responsible for converting the user’s data into delimited strings on the given file-like object
wr = csv.writer(file)

In [41]:
# Write all elements in rows
wr.writerows(matrix)
file.close()

In [42]:
readfile = open("matrix.csv","r") #opens file stream

In [43]:
loaded_csv = csv.reader(readfile) #reads the csv file to lmatrix
data = []

for row in loaded_csv:
 data.append(row)

print(data)
#readfile.close() #closes file stream

[['0.6298589005569739', '0.916389739995089', '0.41438391070124736', '0.09860004539551948', '0.46438036230903834'], [], ['0.9268846354799861', '0.7706181288835423', '0.17839554964401771', '0.992067633308055', '0.3342833746433532'], [], ['0.4906213950305435', '0.3928637891212421', '0.5086225029056533', '0.9848595844413045', '0.9363387614226841'], [], ['0.06972556077565983', '0.6130084221321831', '0.9806547183629536', '0.4581124989741363', '0.13982784168069662'], [], ['0.5280623391526317', '0.3331894150563063', '0.7059333384480849', '0.7757627099578932', '0.38000097291424106'], []]


In [44]:
readfile

<_io.TextIOWrapper name='matrix.csv' mode='r' encoding='cp1252'>

In [45]:
print(readfile.read())